nav:
  Home: /
  About: /about/
  Writing: /posts/
  Projects: http://github.com/zkep

projects_url: http://github.com/zkep

customize:
  gravatar:
    email:
  logo:
    enabled: true
    width: 50
    height: 50
    #url: /images/logo.png
    url: https://avatars.githubusercontent.com/u/36965534
    gravatar: false
  favicon:
    # eg. generate with http://realfavicongenerator.net/
    desktop:
      url: /images/favicon.ico
      gravatar: false
    android:
      url: /images/favicon-192x192.png
      gravator: false
    apple:
      url: /images/apple-touch-icon.png
      gravator: false
  social_links:
    github: http://github.com/zkep
  show_all_posts: true
  post_count: 10
  highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
  disqus_shortname: # Disqus Comments Shortname
  google_analytics: UA-37473492-6 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
